# Copy output from data-preparation into input folder 
library(here)
file.copy(here("gen", "analysis", "output", "boxplot_anger.pdf"), here("gen", "paper", "input", "boxplot_anger.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_anticipation.pdf"), here("gen", "paper", "input", "anticipation.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_disgust.pdf"), here("gen", "paper", "input", "boxplot_disgust.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_fear.pdf"), here("gen", "paper", "input", "boxplot_fear.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_joy.pdf"), here("gen", "paper", "input", "boxplot_joy.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_negative.pdf"), here("gen", "paper", "input", "boxplot_negative.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_positive.pdf"), here("gen", "paper", "input", "boxplot_positive.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_sadness.pdf"), here("gen", "paper", "input", "boxplot_sadness.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_surprise.pdf"), here("gen", "paper", "input", "boxplot_surprise.pdf"))
file.copy(here("gen", "analysis", "output", "boxplot_trust.pdf"), here("gen", "paper", "input", "boxplot_trust.pdf"))
file.copy(here("gen", "analysis", "output", "plot_emotions_sum.pdf"), here("gen", "paper", "input", "plot_emotions_sum.pdf"))
file.copy(here("gen", "analysis", "output", "plot_posneg_sum.pdf"), here("gen", "paper", "input", "plot_posneg_sum.pdf"))
file.copy(here("gen", "analysis", "output", "plot_wordcount_sum.pdf"), here("gen", "paper", "input", "plot_wordcount_sum.pdf"))
